[project]
name = "Flask_API_Json"
description = "A simple task application, written in Flask, using Python and a json data file."
version = "0.0.1"
readme = "README.md"
dependencies = [
    "Flask >= 3.1.0", "Pytest >= 8.3.3", ]